dist: trusty

language: scala

jdk:
  - oraclejdk8

scala:
  - 2.11.8

before_script:
  - cd shine
  - cp conf/application-docker.conf conf/application.conf
  - echo "Determining dependency tree..."
  - sbt "inspect tree clean"

script:
  - sbt compile

